# Generated by Django 5.2.7 on 2025-10-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_vendor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToEatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.counter')),
                ('item_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.itemvariation')),
            ],
        ),
    ]
