# Generated by Django 5.2.7 on 2025-11-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariation',
            old_name='item',
            new_name='menu_item',
        ),
    ]
