# Generated by Django 5.2.7 on 2025-11-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_item_itemvariation_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readytoeatitem',
            name='discounted_price',
        ),
    ]
