# Generated by Django 5.2.7 on 2025-11-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_readytoeatitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='counter_images/'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='counter',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.vendor'),
        ),
    ]
