# Generated by Django 5.2.7 on 2025-11-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_item_itemvariation_menu_item'),
        ('orders', '0006_order_cancelled_at_order_is_ready_to_eat_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='claimed_rte_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_by_cart_item', to='menu.readytoeatitem'),
        ),
    ]
