# Generated by Django 5.2.7 on 2025-11-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_item_itemvariation_menu_item'),
        ('orders', '0007_cartitem_claimed_rte_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='claimed_rte_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_by_order_item', to='menu.readytoeatitem'),
        ),
    ]
