# Generated by Django 5.2.7 on 2025-11-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_counter_image_alter_counter_description_and_more'),
        ('orders', '0009_order_is_paid_order_order_id_razorpay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='claimed_rte_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='menu.readytoeatitem'),
        ),
    ]
